name: Sitemap Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # يومي (تقدر تغيره)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: videos-data
          path: output.xlsx
